resolver: lts-11.8

packages:
- .
- location:
    git: https://github.com/bitemyapp/esqueleto.git
    commit: 632f4408df05501b02d3e2f951bfdd335ea515ba
  extra-dep: true

extra-deps:
  - random-strings-0.1.1.0
